### ISSUE TITLE
Make it run faster, just for fun

### ISSUE THREAD

**Issue by rx80** [tsoding/vodus#1]
At least on my machine, with default compression:
```
real    0m7.369s
user    0m26.864s
sys     0m0.898s
```
And with RLE compression: 2-3 sec

A drop-in replacement for `save_image32_as_png`:
```c
#include <zlib.h>

int save_image32_as_png(Image32 image, const char *filename)
{
    FILE *fp = fopen(filename, "wb");
    if (fp == NULL) return -1;

    png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING, 0, 0, 0);
    if (png_ptr == NULL) {
        fclose(fp);
        return -1;
    }

    png_infop info_ptr = png_create_info_struct(png_ptr);
    if (info_ptr == NULL) {
        fclose(fp);
        png_destroy_write_struct(&png_ptr, 0);
    }

    if (setjmp(png_jmpbuf(png_ptr))) {
      fclose(fp);
      png_destroy_write_struct(&png_ptr, &info_ptr);
      return -1;
   }

    png_init_io(png_ptr, fp);
    png_set_filter(png_ptr, PNG_FILTER_TYPE_BASE, PNG_FILTER_SUB);
    png_set_compression_strategy(png_ptr, Z_RLE);
    png_set_compression_level(png_ptr, 1);
    png_set_IHDR(png_ptr, info_ptr,
        image.width, image.height,
        8, /* DEPTH */
        PNG_COLOR_TYPE_RGBA,
        PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_BASE,
        PNG_FILTER_TYPE_BASE
    );
    png_set_gAMA(png_ptr, info_ptr, 2.2);
    png_write_info(png_ptr, info_ptr);
    //png_set_bgr(png_ptr);
    png_set_swap(png_ptr);

    png_bytep row_pointers[image.height];
    int bytes_per_pixel = 4;
    for (int k = 0; k < image.height; k++)
        row_pointers[k] = (png_bytep)image.pixels + k*image.width*bytes_per_pixel;

    png_write_image(png_ptr, row_pointers);
    png_write_end(png_ptr, info_ptr);
    png_destroy_write_struct(&png_ptr, &info_ptr);

    if (fclose(fp) == 0) return 0;
    (void)fclose(fp);
    (void)remove(filename);
    return -1;
}
```

**Comment by rexim** [comment]
On my machine:
```
real	0m59.753s
user	0m8.523s
sys	0m3.343s
```

**Comment by rexim** [comment]
I think my hard drive is just very slow and that's why compression actually improves the performance on my machine.

**Comment by rexim** [comment]
Just an interesting observation

Original code:
![2020-02-13-103230_1197x444_scrot](https://user-images.githubusercontent.com/165283/74399121-4af0d680-4e4c-11ea-8755-8df03650e172.png)

Your changes:
![2020-02-13-103257_1021x424_scrot](https://user-images.githubusercontent.com/165283/74399136-53491180-4e4c-11ea-9d9b-05a94af5644c.png)

The D-s (uninterruptible sleep) on the second image and the lack of CPU activity indicate that the threads probably spend majority of their time on IO. Which I guess could be slow if the IO is slow lol.

**Comment by rx80** [comment]
Ah, makes sense. I did some more checking on my machine. It's only fast (i think) because i got enough ram for all the stuff to be in buffers instead of being written.

**Comment by rx80** [comment]
The optimal solution would of course be to somehow pipe the output directly into ffmpeg, instead of writing images to disk. But not sure if i'm clever enough to do that :D

**Comment by rx80** [comment]
For enabled compression, but still fast:
```
png_set_compression_strategy(png_ptr, Z_RLE); //this needs zlib.h
png_set_compression_level(png_ptr, 1); //6 is default, 1-3 should be fast but still compress a lot
```

**Comment by rexim** [comment]
@rx80 it actually worked! Too bad we gonna remove this entire code soon when we integrate with ffmpeg.

![2020-02-19-235152_263x91_scrot](https://user-images.githubusercontent.com/165283/74855117-d39ed380-5372-11ea-9536-e7e8bd5fa8d5.png)

**Comment by rexim** [comment]
Invalidated by #2
