### ISSUE TITLE
expired cert 

### ISSUE THREAD

**Issue by brahmanoomer** [tsoding/vodus#121]
```
root@35ffa8465d8e:/vodus/third_party# ./build_third_party.sh
--2020-09-17 17:28:16--  https://deac-riga.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
Resolving deac-riga.dl.sourceforge.net (deac-riga.dl.sourceforge.net)... 89.111.52.100
Connecting to deac-riga.dl.sourceforge.net (deac-riga.dl.sourceforge.net)|89.111.52.100|:443... connected.
ERROR: The certificate of 'deac-riga.dl.sourceforge.net' is not trusted.
ERROR: The certificate of 'deac-riga.dl.sourceforge.net' has expired.
The certificate has expired
```

https://www.ssllabs.com/ssltest/analyze.html?d=deac-riga.dl.sourceforge.net

**Comment by rexim** [comment]
@brahmanoomer I checked the ssllabs link and the cert appears to be valid until Sat, 14 Nov 2020 03:03:14 UTC (expires in 1 month and 23 days).

Are you sure this is not something on your side? SO suggests that it might be related to DNS cache problems. So I disabled DNS cache explicitly in `wget` commands of `build_third_party.sh` in 54dba12934a97cdadee37dec6efe543ca2840d5f

Please let me know if that fixes anything for you.

**Comment by brahmanoomer** [comment]
I re-ran the `wget "https://deac-riga.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz"` (without disabling cache) just now and it works. 

I didn't disable cache when I first encountered the problem, so it's possible it might've fixed it, although when I encoutnered the problem 4 days ago, the website was indicating that the cert was expired, so maybe it wasn't on my end.
