### ISSUE TITLE
multiple input log files support?

### ISSUE THREAD

**Issue by rexim** [tsoding/vodus#68]
introduced in #67

```
./vodus sample-1.txt sample-2.txt ...
```

Should produce a sequence of files: `sample-1.mpeg, sample-2.mpeg, ...`

**Comment by camjac251** [comment]
Would it be possible to support Overrustle as an input?

It's formatted a bit differently than the format I saw on your stream.
```
[2019-06-06 23:59:44 UTC] username2: @username it's HORRIBLE pepeD
[2019-06-06 23:59:53 UTC] username3: WOOOOOOOOOOOOOOOOOOOO
[2019-06-06 23:59:54 UTC] username3: WOOOOOOOOOOOOOOOOOOOO
[2019-06-06 23:59:55 UTC] username3: WOOOOOOOOOOOOOOOOOOOO
[2019-06-06 23:59:55 UTC] username3: WOOOOOOOOOOOOOOOOOOOO
```

**Comment by rexim** [comment]
@camjac251 I'll think about it, thanks for bringing it up! Created a separate issue for this #69

**Comment by rexim** [comment]
@camjac251 oh, wait, I'm pepege :D

**Comment by camjac251** [comment]
Do you have discord? I could send more examples of the logs if helpful.

**Comment by camjac251** [comment]
This project might also be helpful. It can render the chat using Overrustle logs but it currently doesn't have any emote support
https://github.com/abekashem/TwitchChatOverlay

**Comment by rexim** [comment]
Vodus has a completely different command line and configuration syntax. This issue does not particularly make sense anymore.
