### ISSUE TITLE
gif rendering does not handle disposal flags correctly

### ISSUE THREAD

**Issue by rexim** [tsoding/vodus#97]
introduced in #96

**Comment by FrankGrimm** [comment]
![image](https://user-images.githubusercontent.com/321111/88840521-eac4d580-d1dc-11ea-887c-70ef08e61d56.png)

http://giflib.sourceforge.net/whatsinagif/animation_and_transparency.html#animation 

> The disposal method specifies what happens to the current image data when you move onto the next. We have three bits which means we can represent a number between 0 and 7. Our sample animated image has a value of 1 which tells the decoder to leave the image in place and draw the next image on top of it. A value of 2 would have meant that the canvas should be restored to the background color (as indicated by the logical screen descriptor). A value of 3 is defined to mean that the decoder should restore the canvas to its previous state before the current image was drawn. I don't believe that this value is widely supported but haven't had the chance to test it out.

**Comment by rexim** [comment]
@FrankGrimm thank you so much! This is very useful! :)
