### ISSUE TITLE
build_third_party.sh fails on FreeBSD

### ISSUE THREAD

**Issue by herrhotzenplotz** [tsoding/vodus#99]
As of commit  71391aec29a6ff5cccb8a9719654f7546081bbdc

Tested on:

```bash
[nico@triton ~/Source/vodus/third_party (master)]$ uname -apKU
FreeBSD triton 12.1-RELEASE FreeBSD 12.1-RELEASE r363123 TRITON  amd64 amd64 1201000 1201000
```

Log:

https://gist.githubusercontent.com/herrhotzenplotz/7fe9f02f7a473b539c352e4bffaf0c70/raw/cb4f7d46a988efb4d914ea230909c8aa0a45f2e0/vodus.thirdparty.log

**Comment by rexim** [comment]
@herrhotzenplotz oh this is interesting! Looks like the build fails on trying to link the executable utilities that come with giflib. I wonder if it's possible to configure the build so it only build the library. :thinking: I have no idea how to do that since the project doesn't have any `configure` script...

**Comment by herrhotzenplotz** [comment]
@rexim I'll have a look into this later this or next week. 
Concerning the ffmpeg issues, well, idk. I'll consult the ports tree. Maybe there is some useful info in the patches.

**Comment by herrhotzenplotz** [comment]
@rexim After I had a quick look at the logs, I realized that there are some double white spaces in the linker command, which is usually a hint that the FreeBSD make did not define the macros `$<` `$^` and `$@`.
After hacking the build script such that it uses `gmake` as a make command, the whole thing built without errors (but still warnings).
Having in mind, that the build process requires GNU make in general because the dependencies need to be built with it, it might be feasible to just drop support for BSD make (although this is not desirable).

If you don't mind, I'll extend the build script to recognize the OS and select the appropriate make command and submit a PR.

**Comment by rexim** [comment]
@herrhotzenplotz if there is nothing left on this issue to be done, please close it. Thanks!
